# Generated by Django 5.2.8 on 2025-12-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='prosthesiscontrol',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='patient',
            name='ci',
            field=models.CharField(max_length=12, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='ClinicalRecord',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ProsthesisControl',
        ),
    ]
