# Generated by Django 5.2.8 on 2025-12-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosthesis',
            name='etapa',
            field=models.CharField(choices=[('cubeta', 'Cubeta individual'), ('placa', 'Placa articular (rodete)'), ('enfilado', 'Enfilado'), ('terminacion', 'Terminación')], max_length=200),
        ),
    ]
