# Generated by Django 5.2.8 on 2025-12-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_prosthesis_etapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='prosthesis',
            old_name='fecha_recepcion',
            new_name='fecha_retorno',
        ),
    ]
