# Generated by Django 5.2.8 on 2025-12-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='categoria',
        ),
        migrations.AddField(
            model_name='inventory',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock_bajo',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='proveedor',
            field=models.CharField(blank=True, default='Desconocido', max_length=200),
            preserve_default=False,
        ),
    ]
