# Generated by Django 5.2.8 on 2025-12-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_inventory_categoria_inventory_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
