# Generated by Django 5.2.8 on 2025-12-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_budgetitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetitem',
            old_name='total',
            new_name='total_item',
        ),
    ]
