# Generated by Django 5.2.8 on 2025-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_total_budgetitem_total_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stock_bajo',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_stock',
            field=models.IntegerField(default=5, verbose_name='Stock mínimo'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
            preserve_default=False,
        ),
    ]
