# Generated by Django 5.2.8 on 2025-12-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_inventory_cantidad_remove_inventory_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
