# Generated by Django 5.2.8 on 2025-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_inventory_supplier_inventory_proveedor_and_more'),
    ]


    operations = [
        migrations.AddField(
            model_name='patient',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
