# Generated by Django 5.2.8 on 2025-12-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_patient_fecha_nacimiento'),
    ]


    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='paciente',
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='core.patient'),
            preserve_default=False,
        ),
    ]
