# Generated by Django 5.2.8 on 2025-12-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_clinicalrecord_patient'),
        ('core', '0022_fix_patient_fecha_nacimiento'),
    ]

    operations = [
    ]
