# Generated by Django 5.2.8 on 2025-12-28 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20251227_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='paciente',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='clinical_records',
                to='core.patient',
            ),
        ),

    ]
