# Generated by Django 5.2.8 on 2025-12-29 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_clinicalrecord_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='core.patient'),
        ),
    ]
