# Generated by Django 5.2.8 on 2025-12-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rayosx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayosx',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayos_x', to='core.patient'),
        ),
    ]
