# Generated by Django 5.2.8 on 2026-02-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_rayosx_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('asistio', 'Asistió'), ('no_asistio', 'No asistió'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
