# Generated by Django 5.2.8 on 2026-03-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_appointment_options_alter_appointment_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En proceso'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=30, null=True)),
                ('tipo', models.CharField(choices=[('sena', 'Seña'), ('pago_parcial', 'Pago parcial'), ('pago_final', 'Pago final')], default='sena', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.budget')),
            ],
        ),
    ]
