# Generated by Django 5.2.8 on 2026-03-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_budget_estado_budgetpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedimientos',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='core.procedure', verbose_name='Procedimientos'),
        ),
    ]
