# Generated by Django 5.2.8 on 2026-04-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_procedure_appointment_procedimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
