# Generated by Django 5.2.8 on 2026-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_appointment_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto total'),
        ),
    ]
