# Generated by Django 5.2.8 on 2026-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_appointment_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ci',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
