# Generated by Django 5.2.8 on 2026-04-28 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_patient_ci_alter_patient_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetpayment',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='budgetpayment',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
