# Generated by Django 5.2.8 on 2026-05-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_budgetpayment_fecha_alter_budgetpayment_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='cardiopatia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='cirugias_previas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='consentimiento_aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='consentimiento_explicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='consentimiento_firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='hta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='medicacion_actual',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='ninguno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='otros_antecedentes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='pronostico',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('reservado', 'Reservado'), ('malo', 'Malo')], max_length=10),
        ),
    ]
