# Generated by Django 5.2.8 on 2026-05-01 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_fix_clinicalrecord_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdontogramTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado'), ('ausente', 'Ausente'), ('corona', 'Corona'), ('movilidad', 'Movilidad'), ('extraccion', 'Extracción')], default='sano', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='core.patient')),
            ],
        ),
    ]
