# Generated by Django 5.2.8 on 2026-05-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_odontogramtooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontogramtooth',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='odontogramtooth',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
    ]
