# Generated by Django 5.2.8 on 2026-05-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_odontogramtooth_pos_x_odontogramtooth_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='evolucion',
            field=models.TextField(blank=True),
        ),
    ]
