# Generated by Django 5.2.8 on 2026-06-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_dayblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('En espera', 'En espera'), ('confirmado', 'Confirmado'), ('asistio', 'Asistió'), ('no_asistio', 'No asistió'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='OdontogramaCara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.CharField(max_length=5)),
                ('cara', models.CharField(choices=[('vestibular', 'Vestibular'), ('mesial', 'Mesial'), ('distal', 'Distal'), ('oclusal', 'Oclusal / Incisal'), ('palatino_lingual', 'Palatino / Lingual')], max_length=30)),
                ('estado', models.CharField(choices=[('caries', 'Caries'), ('obturado', 'Obturado'), ('corona', 'Corona'), ('endodoncia', 'Endodoncia'), ('implante', 'Implante'), ('extraccion', 'Extracción indicada'), ('ausente', 'Ausente'), ('sano', 'Sano')], max_length=30)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma_caras', to='core.patient')),
            ],
            options={
                'ordering': ['pieza', 'cara'],
                'unique_together': {('paciente', 'pieza', 'cara')},
            },
        ),
    ]
