# Generated by Django 5.2.8 on 2026-06-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_appointment_estado_odontogramacara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontogramtooth',
            name='estado',
            field=models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado'), ('corona', 'Corona'), ('endodoncia', 'Endodoncia'), ('implante', 'Implante'), ('extraccion', 'Extracción'), ('ausente', 'Ausente'), ('movilidad', 'Movilidad')], default='sano', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.inventory')),
            ],
        ),
    ]
