# Generated by Django 5.2.8 on 2026-06-19 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_odontogramtooth_estado_inventorymovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('laboratorio', 'En laboratorio'), ('lista', 'Lista para retirar'), ('entregada', 'Entregada')], default='pendiente', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('protesis_completa', models.BooleanField(default=False)),
                ('protesis_completa_sup', models.BooleanField(default=False)),
                ('protesis_completa_inf', models.BooleanField(default=False)),
                ('protesis_parcial', models.BooleanField(default=False)),
                ('protesis_parcial_sup', models.BooleanField(default=False)),
                ('protesis_parcial_inf', models.BooleanField(default=False)),
                ('protesis_flexible', models.BooleanField(default=False)),
                ('protesis_flexible_sup', models.BooleanField(default=False)),
                ('protesis_flexible_inf', models.BooleanField(default=False)),
                ('cromo', models.BooleanField(default=False)),
                ('cromo_sup', models.BooleanField(default=False)),
                ('cromo_inf', models.BooleanField(default=False)),
                ('provisorio_placa', models.BooleanField(default=False)),
                ('provisorio_placa_sup', models.BooleanField(default=False)),
                ('provisorio_placa_inf', models.BooleanField(default=False)),
                ('reparacion', models.BooleanField(default=False)),
                ('rebasado', models.BooleanField(default=False)),
                ('cubeta_individual', models.BooleanField(default=False)),
                ('placa_articular', models.BooleanField(default=False)),
                ('enfilado', models.BooleanField(default=False)),
                ('terminacion', models.BooleanField(default=False)),
                ('removible_otros', models.BooleanField(default=False)),
                ('removible_otros_texto', models.CharField(blank=True, max_length=255)),
                ('perno_metalico', models.BooleanField(default=False)),
                ('incrustacion', models.BooleanField(default=False)),
                ('jacket', models.BooleanField(default=False)),
                ('corona', models.BooleanField(default=False)),
                ('puente_fijo', models.BooleanField(default=False)),
                ('contencion', models.BooleanField(default=False)),
                ('contencion_sup', models.BooleanField(default=False)),
                ('contencion_inf', models.BooleanField(default=False)),
                ('placa_relajacion', models.BooleanField(default=False)),
                ('placa_relajacion_sup', models.BooleanField(default=False)),
                ('placa_relajacion_inf', models.BooleanField(default=False)),
                ('ortodoncia_otros', models.BooleanField(default=False)),
                ('ortodoncia_otros_texto', models.CharField(blank=True, max_length=255)),
                ('impresion_inicial', models.BooleanField(default=False)),
                ('impresion_inicial_sup', models.BooleanField(default=False)),
                ('impresion_inicial_inf', models.BooleanField(default=False)),
                ('impresion_definitiva', models.BooleanField(default=False)),
                ('impresion_definitiva_sup', models.BooleanField(default=False)),
                ('impresion_definitiva_inf', models.BooleanField(default=False)),
                ('modelo', models.BooleanField(default=False)),
                ('modelo_sup', models.BooleanField(default=False)),
                ('modelo_inf', models.BooleanField(default=False)),
                ('registro_mordida', models.BooleanField(default=False)),
                ('protesis_a_reparar', models.BooleanField(default=False)),
                ('material_otros', models.BooleanField(default=False)),
                ('material_otros_texto', models.CharField(blank=True, max_length=255)),
                ('indicaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_entrega_prometida', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('protesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_laboratorio', to='core.prosthesis')),
            ],
        ),
    ]
