# Generated by Django 5.2.8 on 2026-06-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_ordenlaboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthesis',
            name='estado',
            field=models.CharField(choices=[('laboratorio', 'En laboratorio'), ('proceso', 'En proceso'), ('prueba', 'Lista para prueba'), ('entrega', 'Lista para entrega'), ('entregada', 'Entregada')], default='laboratorio', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='prosthesis',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio / toma de impresión'),
        ),
        migrations.AddField(
            model_name='prosthesis',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto total'),
        ),
        migrations.AddField(
            model_name='prosthesis',
            name='tipo_protesis',
            field=models.CharField(choices=[('parcial_sup', 'Prótesis parcial superior'), ('parcial_inf', 'Prótesis parcial inferior'), ('total_sup', 'Prótesis total superior'), ('total_inf', 'Prótesis total inferior'), ('total_bimax', 'Prótesis total superior e inferior'), ('flexible', 'Prótesis flexible'), ('esqueletica', 'Prótesis esquelética'), ('corona', 'Corona'), ('puente', 'Puente'), ('rebase', 'Rebase'), ('reparacion', 'Reparación'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de prótesis'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='etapa',
            field=models.CharField(choices=[('impresion', 'Impresión / toma de impresión'), ('cubeta', 'Cubeta individual'), ('rodete', 'Rodete / placa articular'), ('prueba_dientes', 'Prueba de dientes'), ('enfilado', 'Enfilado'), ('terminacion', 'Terminación'), ('entrega', 'Entrega')], default='impresion', max_length=50, verbose_name='Etapa actual'),
        ),
        migrations.AlterField(
            model_name='prosthesis',
            name='trabajo',
            field=models.CharField(max_length=200, verbose_name='Trabajo solicitado'),
        ),
    ]
