# Generated by Django 5.2.8 on 2026-06-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_prosthesis_estado_prosthesis_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosthesis',
            name='trabajo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Trabajo solicitado'),
        ),
    ]
