# Generated by Django 5.2.8 on 2026-06-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_prosthesis_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosthesis',
            name='tipo_protesis',
            field=models.CharField(choices=[('removible', 'Prótesis removible'), ('fija', 'Rehabilitación fija'), ('ortodoncia', 'Ortodoncia y otros'), ('reparacion', 'Reparación / Rebase'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de prótesis'),
        ),
    ]
