# Generated by Django 5.2.8 on 2026-07-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_prosthesis_tipo_protesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('realizado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_recordatorios', to='core.patient')),
            ],
            options={
                'verbose_name': 'Recordatorio de agenda',
                'verbose_name_plural': 'Recordatorios de agenda',
                'ordering': ['realizado', 'fecha', '-id'],
            },
        ),
    ]
