# Generated by Django 5.2.8 on 2026-08-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_ordenlaboratorio_hora_solicitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='historia_actualizada',
            field=models.BooleanField(default=False),
        ),
    ]
