# Generated by Django 5.2.8 on 2026-08-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_appointment_historia_actualizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(default='Horario bloqueado', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'hora'), name='unique_time_block_fecha_hora')],
            },
        ),
    ]
