# Generated by Django 5.2.8 on 2026-08-13 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_timeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_alerts', to='core.patient')),
            ],
            options={
                'verbose_name': 'Aviso clínico',
                'verbose_name_plural': 'Avisos clínicos',
                'ordering': ['realizado', 'fecha_revision', '-creado'],
            },
        ),
    ]
