# Generated by Django 5.2.8 on 2026-09-20 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_prosthesis_trabajos_unificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
